# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eclat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eclat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65\x63lat.proto\"!\n\x0f\x45\x63latRunRequest\x12\x0e\n\x06script\x18\x01 \x01(\t\"3\n\x10\x45\x63latRunResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t25\n\x05\x45\x63lat\x12,\n\x03Run\x12\x10.EclatRunRequest\x1a\x11.EclatRunResponse\"\x00\x62\x06proto3'
)




_ECLATRUNREQUEST = _descriptor.Descriptor(
  name='EclatRunRequest',
  full_name='EclatRunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='script', full_name='EclatRunRequest.script', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=48,
)


_ECLATRUNRESPONSE = _descriptor.Descriptor(
  name='EclatRunResponse',
  full_name='EclatRunResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='EclatRunResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='EclatRunResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['EclatRunRequest'] = _ECLATRUNREQUEST
DESCRIPTOR.message_types_by_name['EclatRunResponse'] = _ECLATRUNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EclatRunRequest = _reflection.GeneratedProtocolMessageType('EclatRunRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECLATRUNREQUEST,
  '__module__' : 'eclat_pb2'
  # @@protoc_insertion_point(class_scope:EclatRunRequest)
  })
_sym_db.RegisterMessage(EclatRunRequest)

EclatRunResponse = _reflection.GeneratedProtocolMessageType('EclatRunResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECLATRUNRESPONSE,
  '__module__' : 'eclat_pb2'
  # @@protoc_insertion_point(class_scope:EclatRunResponse)
  })
_sym_db.RegisterMessage(EclatRunResponse)



_ECLAT = _descriptor.ServiceDescriptor(
  name='Eclat',
  full_name='Eclat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=103,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='Eclat.Run',
    index=0,
    containing_service=None,
    input_type=_ECLATRUNREQUEST,
    output_type=_ECLATRUNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECLAT)

DESCRIPTOR.services_by_name['Eclat'] = _ECLAT

# @@protoc_insertion_point(module_scope)
