EXTERNAL_MAKEFILE_PATH= "hike_v3/external/Makefile"
HIKE_SOURCE_PATH = "hike_v3/src/"
HIKE_CC = "hike_v3/hike-tools/hikecc.sh"
BUILD_DIR = "runtime/output/"
MAP_PATH = "/sys/fs/bpf/maps/hike_chain_map"
